stages:
  load_data:joblib
    cmd: python src/load_data_flight.py --config=params_flight.yaml
    deps:
    - src/get_data_flight.py
    - src/load_data_flight.py
    - source_code/flight_course5i.csv

    outs:
    - data/raw/flight_course5i.csv

  split_data:
    cmd: python src/split_data_flight.py --config=params_flight.yaml
    deps:
    - src/split_data_flight.py
    - data/raw/flight_course5i.csv

    outs:
    - data/processed/train_flight_course5i.csv
    - data/processed/test_flight_course5i.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate_flight.py --config=params_flight.yaml
    deps:
    - data/processed/train_flight_course5i.csv
    - data/processed/test_flight_course5i.csv
    - src/train_and_evaluate_flight.py

    params:
    - estimators.RandomForest.params.n_estimators
    - estimators.RandomForest.params.max_depth
    - estimators.XGBoost.params.n_estimators
    - estimators.XGBoost.params.max_depth
    - estimators.XGBoost.params.learning_rate

    metrics:
    - reports/scores_flight.json
      cache: false
    - reports/params_flight.json
      cache: false
    outs:
    - models/model_flight.joblib